#*  Copyright (C) 2018 the DEUS contributors.
#*  Website: https://github.com/timjeske/DEUS
#*
#*  This file is part of the KNIME4NGS KNIME extension.
#*
#*  The DEUS R package is free software: you can redistribute it and/or modify
#*  it under the terms of the GNU General Public License as published by
#*  the Free Software Foundation, either version 3 of the License, or
#*  (at your option) any later version.
#*
#*  This program is distributed in the hope that it will be useful,
#*  but WITHOUT ANY WARRANTY; without even the implied warranty of
#*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#*  GNU General Public License for more details.
#*
#*  You should have received a copy of the GNU General Public License
#*  along with this program.  If not, see <http://www.gnu.org/licenses/>.



#' Function to blast small RNA sequences.
#'
#' This function takes a vector of sequences in fasta style as input and blasts them using a local blast database.
#' The parameters are configured for blasting small RNA sequences with 100\% identity over the whole query sequence.
#'
#' @param blast_exec path to your installation of 'blastn'
#' @param blast_db path to your local blastdb
#' @param ncores number of cores used for blasting
#' @param sig_sequences vector of sequences in fasta style generated by the sequencesAsFasta
#' @param strand query strand(s) to search against database, default = 'plus'
#' @param identity identity cutoff applied for filtering blast results
#' @param dust specifies whether low complexity filter is applied on query (default=no)
#' @param soft_masking specifies whether low complexity filter is applied on database (default=no)
#' @keywords blastn
#' @export
#' @examples
#' blast_exec <- "$HOME/software/ncbi-blast-2.6.0+/bin/blastn"
#' blast_db <-"$HOME/blastdb/MouseDB.fa"
#' ncores <- 2
#' testseq <- c(">seq_1","GCATTGGTGGTTCAGTGGTAGAATTCTCGCC")
#' blastResult <- runBlast(blast_exec, blast_db, ncores, testseq)

runBlast <- function(blast_exec, blast_db, ncores, sig_sequences, strand = 'plus', identity=100, dust='no', soft_masking='false') {
  blast.f6 <- c('qseqid', 'qlen', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart', 'qend', 'sstart' ,'send', 'evalue', 'bitscore')
  command=paste("-db",blast_db, "-num_threads", ncores , "-perc_identity", identity, "-dust", dust, "-soft_masking", soft_masking, "-strand", strand, "-task blastn-short -qcov_hsp_perc 100 -max_target_seqs 2000 -outfmt", sprintf(" '6 %s'",paste(collapse=" ",blast.f6)),sep=" ")
cat("Blastn configuration:\n")
print(paste(blast_exec,command))
  blast.out <- system2(blast_exec,command, input=sig_sequences, stdout=TRUE)
  blast.out.df <- `names<-`(read.table(quote="",sep='\t',textConnection(blast.out)),blast.f6)
  return(blast.out.df)
}
