#' Function to blast small RNA sequences.
#'
#' This function takes a vector of sequences in fasta style as input and blasts them using a local blast database.
#' The parameters are configured for blasting small RNA sequences with 100\% identity over the whole query sequence.
#'
#' @param blast_exec path to your installation of 'blastn'
#' @param blast_db path to your local blastdb
#' @param ncores number of cores used for blasting
#' @param sig_sequences vector of sequences in fasta style generated by the sequencesAsFasta
#' @param strand query strand(s) to search against database, default = 'plus'
#' @keywords blastn
#' @export
#' @examples
#' blast_exec <- "$HOME/software/ncbi-blast-2.6.0+/bin/blastn"
#' blast_db <-"$HOME/blastdb/MouseDB.fa"
#' ncores <- 2
#' testseq <- c(">seq_1","GCATTGGTGGTTCAGTGGTAGAATTCTCGCC")
#' blastResult <- runBlast(blast_exec, blast_db, ncores, testseq)

runBlast <- function(blast_exec, blast_db, ncores, sig_sequences, strand = 'plus', identity=100, dust=no, soft_masking=false) {
  blast.f6 <- c('qseqid', 'qlen', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart', 'qend', 'sstart' ,'send', 'evalue', 'bitscore')
  command=paste("-db",blast_db, "-num_threads", ncores , "-perc_identity", identity, "-strand", strand, "-task blastn-short -qcov_hsp_perc 100 -max_target_seqs 2000 -outfmt", sprintf(" '6 %s'",paste(collapse=" ",blast.f6)),sep=" ")
  blast.out <- system2(blast_exec,command, input=sig_sequences, stdout=TRUE)
  blast.out.df <- `names<-`(read.table(quote="",sep='\t',textConnection(blast.out)),blast.f6)
  return(blast.out.df)
}
