#*  Copyright (C) 2018 the USB contributors.
#*  Website: https://github.com/timjeske/USBseq
#*  
#*  This file is part of the KNIME4NGS KNIME extension.
#*  
#*  The USBseq R package is free software: you can redistribute it and/or modify
#*  it under the terms of the GNU General Public License as published by
#*  the Free Software Foundation, either version 3 of the License, or
#*  (at your option) any later version.
#*  
#*  This program is distributed in the hope that it will be useful,
#*  but WITHOUT ANY WARRANTY; without even the implied warranty of
#*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#*  GNU General Public License for more details.
#*  
#*  You should have received a copy of the GNU General Public License
#*  along with this program.  If not, see <http://www.gnu.org/licenses/>.



#' Function to execute CD-HIT Clustering
#'
#' Sequentially, each sequency is either assinged to an existing cluster or is classified as a new 
#' cluster representative if no matching cluster can be found. 
#'
#' @param cdhit_path Path to cd-hit-est executable
#' @param sequences Vector of sequences in fasta style generated by the sequencesAsFasta
#' @param out_dir Output folder
#' @param identityCutoff Sequence identity cutoff used for clustering
#' @param lengthCutoff Length difference cutoff
#' @param wordlength CD-Hit word length
#' @param map Data frame with sequences as row names and some identifier for each sequence in the first column
#' @param optional Optional execution parameters
#' @keywords clustering
#' @export
#' @examples
#' map <- createMap(sigResults)
#' sigSeqFasta <- sequencesAsFasta(sigResults,map)
#' cd_hit <- "$HOME/software/cdhit/cd-hit-est"
#' clustResult<-runClustering(cd_hit, sigSeqFasta, out_dir, 0.9, 0.9, 9, map)

runClustering <- function(cdhit_path, sequences, out_dir, identityCutoff, lengthCutoff, wordlength, map, optional="") {
  # tmp fasta file
  seq <- paste(out_dir, "sig_sequences.fa", sep="/")
  write.table(sequences, seq,quote = F, row.names = F, col.names = F)

  # run clustering
  clusters <- paste(out_dir,"CD-HIT.fa",sep="/")
  command <- paste("-i",seq,"-c",identityCutoff,"-s",lengthCutoff,"-n",wordlength,"-g 1",optional,"-o",clusters,sep=" ")
  cluster.out <- system2(cdhit_path,command, stdout=TRUE)

  # remove tmp files
  deleteTmp(out_dir)

  # generate result
  out.df <- processClusters(map, clusters, out_dir)
  out.df["sequences"] <- NULL
  names(out.df)<-c("SequenceID","ClusterID")
  return(out.df)
}


#' Processes CD-Hit Outfile
#'
#' @param map data frame with sequences as row names and some identifier for each sequence in the first column
#' @param out_dir Output folder
#' @keywords clustering
#' @export
#' @examples
processClusters <- function(map, clusters, out_dir) {
  cl.dir <- paste(out_dir, "Clusters",sep="/")
  dir.create(cl.dir, showWarnings = FALSE)
  cluster.file <- paste(clusters,".clstr",sep="")
  con <- file(cluster.file, "r")
  out.df <- data.frame()

  while ( TRUE ) {
    line <- readLines(con, n = 1)
    if ( length(line) == 0 ) {
      break
    }
    if(startsWith(line,">")){
      cl_id <- unlist(strsplit(line,"\\s+",perl = T))[2]
    }else{
      seqIDsIndex <- regexpr("seq_[0-9]+",line,perl=TRUE)
      qseqid <- c(regmatches(line, seqIDsIndex))
      out.df <- rbind.data.frame(out.df,cbind(qseqid,cl_id))
    }
  }
  close(con)

  map$sequences<-row.names(map)
  out.df<-merge(x = out.df, y = map, by.x = "qseqid",by.y="seq_id", all.x = TRUE)
  by(out.df,out.df$cl_id,printCluster,cl.dir=cl.dir)
  return(out.df)
}


#' Helper function for generating individual cluster fastas, not meant for external use
#'
#' @param data Subset of overall data provided within the processClusters function
#' @param cl.dir Cluster output folder
#' @keywords clustering
#' @export
#' @examples
printCluster<-function(data,cl.dir){
  cl_id<-data[1,2]
  outfile <- paste(cl.dir,"/Cluster",cl_id,".fa",sep="")
  out<-paste(">",data[,1],"\n",data[,3],sep="")
  write.table(out,outfile,col.names=F,row.names=F,quote=F)
}
