#*  Copyright (C) 2018 the DEUS contributors.
#*  Website: https://github.com/timjeske/DEUS
#*
#*  This file is part of the KNIME4NGS KNIME extension.
#*
#*  The DEUS R package is free software: you can redistribute it and/or modify
#*  it under the terms of the GNU General Public License as published by
#*  the Free Software Foundation, either version 3 of the License, or
#*  (at your option) any later version.
#*
#*  This program is distributed in the hope that it will be useful,
#*  but WITHOUT ANY WARRANTY; without even the implied warranty of
#*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#*  GNU General Public License for more details.
#*
#*  You should have received a copy of the GNU General Public License
#*  along with this program.  If not, see <http://www.gnu.org/licenses/>.


#' Function to generate plots for SummaryTable
#'
#' This function generates a boxplot showing the distribution of BLAST hits for each sncRNA class of interest.
#' Further it plots the number of BLAST hits as a function of the length of the sequences and performs linear regression.
#'
#' @param summary summary table generated by mergeResults function (requires BLAST result)
#' @param classes list of prefixes of features representing classes to be included in the plots
#' @param out_dir directory for plots (boxplot and another one for each class)
#' @keywords summary statistics
#' @export

generateSummaryPlots <- function(summary, classes, out_dir) {

  if(!("FeatureList" %in% names(summary))) stop('Feature classes can only be counted if blast results have been merged to DE results!')
  minql <- min(summary[summary$FeatureList!="NA",]$Length, na.rm=T)
  summary <- summary[summary$Length >= minql,]
  summary[summary == 0] <- NA

  for(i in classes) {
    if(all(is.na(summary[[i]]))) next
    png(paste(out_dir,paste(i,"_length_hits.png",sep=""),sep="/"))
    linearMod <- lm(summary[[i]] ~ summary$Length, data = summary)
    tmp <- summary(linearMod)
    rsq <- tmp$adj.r.squared
    pval <- tmp$coefficients[,"Pr(>|t|)"][2]
    plot(summary$Length, summary[[i]], ylab="BLAST hits", xlab = "Read length in nt", main=paste(i," (Adj. R-squared: ",format.pval(rsq),", p-val: ",format.pval(pval),")",sep=""))
    abline(linearMod, col="red")
    dev.off()
  }

  png(paste(out_dir,"classes_boxplot.png",sep="/"))
  boxplot(summary[,classes], ylab="BLAST hits", main="BLAST hits for each sncRNA class")
  dev.off()
}

#' Function to compute fraction of reads without BLAST hit for each sample
#'
#' @param summary summary table generated by mergeResults function (requires BLAST result)
#' @param countTable table of (normalized) counts per sequence per sample
#' @keywords summary statistics
#' @export

getNoBlastHitFraction <- function(summary, countTable) {

  if(!("FeatureList" %in% names(summary))) stop('Feature classes can only be counted if blast results have been merged to DE results!')

  minql <- min(summary[summary$FeatureList!="NA",]$Length, na.rm=T)
  summary <- summary[summary$Length >= minql,]

  select <- row.names(summary)[summary$FeatureList=="NA"]
  sub <- countTable[as.vector(select),,drop = FALSE]
  res <- colSums(sub)/colSums(countTable)
  res <- as.data.frame(res)
  colnames(res) <- c("NA_fraction")
  res$Sample <- rownames(res)
  res <- res[,c(which(names(res)=="Sample"),which(names(res)!="Sample"))]
  return(res)
}
